version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: techdestination
      POSTGRES_USER: techdest
      POSTGRES_PASSWORD: yoursecurepassword123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  web:
    build: .
    command: bash -c "python manage.py migrate --noinput && gunicorn karmatechdestination.wsgi:application --bind 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=karmatechdestination.settings
      - DATABASE_URL=postgres://techdest:yoursecurepassword123@db:5432/techdestination?sslmode=disable
      - DJANGO_SECRET_KEY=django-insecure-techdestination-key
      - DJANGO_DEBUG=True
    restart: unless-stopped

volumes:
  postgres_data: