version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: carelinktech
      POSTGRES_USER: carelink
      POSTGRES_PASSWORD: carelinkpass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - carelinknet

  web:
    build: .
    command: bash -c "python manage.py migrate --noinput && gunicorn carelinktech.wsgi:application --bind 0.0.0.0:8000"
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://carelink:carelinkpass@db:5432/carelinktech
      - DJANGO_SECRET_KEY=your-secret-key-here
      - DJANGO_DEBUG=True
    depends_on:
      - db
    networks:
      - carelinknet
    volumes:
      - .:/app
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  carelinknet:
    driver: bridge